CREATE TABLE courses(
    id UUID PRIMARY KEY UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    active TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);